### ISSUE TITLE
Provider C2 and VPS servers

### ISSUE THREAD

**Issue by arianvp** [hex-sh/terraform-provider-scaleway#12]
Scaleway also offers VPS servers and C2 servers which are x86 instead of ARM.

A few things to take into account here:
- An ARM volume will not boot on an x86 server and vica versa.
- The current Scaleway API doesn't seem to have documented how to spin up VPS and C2 instances.

**Comment by moul** [comment]
@arianvp, we updated the scaleway-cli/pkg/api package with new servers support, however, the API documentation is not yet updated

cc @quentinperez

**Comment by QuentinPerez** [comment]
Hi @arianvp 

We need to update the documentation 🙂
I took a look at your code, and it's easy to you to start C2 or VPS servers
You must specify the commercial type like below:

https://github.com/hex-sh/terraform-provider-scaleway/blob/master/resource_server.go#L69-L73

``` go
var def api.ScalewayServerDefinition // this struct has a new field `CommercialType`

def.Name = d.Get("name").(string)
def.Image = &image
def.Volumes = volumes
def.CommercialType = // "C1" | "VC1 | C2[SML]"
```

**Comment by arianvp** [comment]
Thanks!

**Comment by arianvp** [comment]
@moul Is there a testing API server I could use that spins up 'fake' servers? A mock API server? Testing is a bit expensive currently because every time I need to debug something I'm paying hosting fees for an hour.

**Comment by moul** [comment]
@arianvp, we don't have a testing API nor real mocks, we only have a static mock which won't support any workflow using POST

Please contact the support so we can add a discount on your account
