### ISSUE TITLE
Add option to associate existing IP to a new instance.

### ISSUE THREAD

**Issue by seb2411** [hex-sh/terraform-provider-scaleway#15]
Hello !

It could be really useful to be able to associate a public IP with a new server.

Thx for the job you are doing ;) .

**Comment by arianvp** [comment]
Yes i have this implemented already!  I will write some documentation

**Comment by sebastien-lemarinel** [comment]
Ok Thx.

**Comment by seb2411** [comment]
Ok Thx.

**Comment by arianvp** [comment]
Example usage:

```
resource "scaleway_server" "loadbalancer" {
  name = "Load balancer"
  image = "dd17877a-4dc8-4d94-82f5-05019b7f6d67"
  type = "VC1S"
}

resource "scaleway_ip"  "loadbalancer_ip" {
  server = "${scaleway_server.loadbalancer.id}"
}
```

**Comment by seb2411** [comment]
Sorry I mean an **existing** (or reserved) IP. As I understand in this example you associate an new public IP to the server ?

**Comment by arianvp** [comment]
All IPs need to be known by  Terraform in advance. Terraform doesn't support talking to resources that weren't created through terraform.     You'll have to creat `scaleway_ip` resources in advance in your terraform file, and then later assign them to servers. Assigning them to servers is optional by the way, so this is valid too:

```
resource "scaleway_server" "loadbalancer" {
  name = "Load balancer"
  image = "dd17877a-4dc8-4d94-82f5-05019b7f6d67"
  type = "VC1S"
}

resource "scaleway_ip"  "loadbalancer_ip" {
  server = "${scaleway_server.loadbalancer.id}"
}

resource "scaleway_ip" "another_reserved_ip" {
# Note that this hasnt been attached to a server yet
}
```

Then later (in a new commit), you could decide to assign the reserved IP to a server:

```
resource "scaleway_ip" "another_reserved_ip" {
  server = "${scaleway_server.my_server.id}"
}
```

**Comment by arianvp** [comment]
To further answer your question,  Once you have an IP resource, nothing stops you from detaching it from a server, and then re-attaching it to another server.

**Comment by seb2411** [comment]
Ok thank you to taking time to respond to my questions. I'm new with Terraform so I still have to understand the complete workflow.

I have to test that.
