### ISSUE TITLE
Add a ip resource

### ISSUE THREAD

**Issue by arianvp** [hex-sh/terraform-provider-scaleway#3]

**Comment by arianvp** [comment]
Depends on https://github.com/scaleway/scaleway-cli/issues/178

**Comment by moul** [comment]
For your information, we can assign ips using **PUT/PATCH** on **servers** OR **PUT/PATCH** on **ips** resources, but in **scaleway-cli** we will work on the **ips** resource

**Comment by arianvp** [comment]
That's similar to https://www.terraform.io/docs/providers/aws/r/eip.html so that's good. As it's how people that use terraform expect it to work.
