### ISSUE TITLE
Add an image resource

### ISSUE THREAD

**Issue by arianvp** [hex-sh/terraform-provider-scaleway#4]

**Comment by arianvp** [comment]
Sizes are integer values in the API.  so it's hard to write "1GB". Terraform should supports units of measure in integer literals though https://www.terraform.io/docs/configuration/syntax.html

**Comment by arianvp** [comment]
Currently that doesn't seem to work. Bug has been reported upstream https://github.com/hashicorp/terraform/issues/3287

**Comment by moul** [comment]
Hi @arianvp,

In scaleway-cli we are already using sizes in a human format, i.e: `scw create 5GB`

The code is actually included in the helpers functions of the API you are using: https://github.com/scaleway/scaleway-cli/blob/master/pkg/api/helpers.go#L304

Using: https://github.com/dustin/go-humanize

I hope it may help

**Comment by arianvp** [comment]
@moul Awesome that will definitely help for now.

**Comment by arianvp** [comment]
Images are just fixed predefined UUIDs.   How these images are created and what their lifecycle is is better solved by a tool like https://www.packer.io/   . I'll see if I can get something going for this at https://github.com/hex-sh/packer-builder-scaleway
